server:
  port: 8080

spring:
  application:
    name: cloud-order-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver #mysql驱动包
    url: jdbc:mysql://localhost:3306/springbootcloud_learn?usrUnicde=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
eureka:
  client:
    #表示是否将自己注册进EurekaServer 默认为true
    register-with-eureka: true
    #表示从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka

mybatis:
  mapper-Locations: classpath:mapper/*.xml
  type-aliases-package: com.viper.springcloud.entites
